version: '3'

services:
  productivity-app:
    container_name: productivity-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/db/prod.db
      - NEXTAUTH_SECRET=changereplacemeplease
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - ./db:/app/db
    restart: always
